### ISSUE TITLE
I have a question about GPU capabilities.

### ISSUE THREAD

**Issue by KATSU-HIGH5** [paul007pl/VRCNet#1]
I'm trying to train VRCNet, but it runs out of RAM when the batch size is more than 16.
The GPU I am using is a GTX 1080 with 8GB.
What kind of GPU are you using and what batch size are you training?

**Comment by paul007pl** [comment]
For most experiments, we use a V100 GPU (32GB) with batch size 32.
If you are using other GPUs with smaller memory, you can try a smaller batch size.
According to my experience, it won't affect a lot.

**Comment by KATSU-HIGH5** [comment]
Thank you very much！！
