### ISSUE TITLE
VRCNet test my data

### ISSUE THREAD

**Issue by KATSU-HIGH5** [paul007pl/VRCNet#10]
I want to do some tests with my point cloud data, but I don't know the structure of the .h5 file.
What is the structure of the file and how was it created? Please let me know.
In addition, how much point cloud data do I need to prepare if I want to train with my point cloud data?

**Comment by paul007pl** [comment]
Thanks for the questions.
1. "how to create h5 files": I am using python lib "h5py", and you can learn form this link: https://docs.h5py.org/en/stable/quick.html
2. "how to decide the size of point cloud dataset": It is not easy to answer.  Usually, we need to perform experiments on datasets with different sizes, and then select a most suitable one by making a trade-off between efficiency and accuracy.
