### ISSUE TITLE
config file for vrcnet with 16384 points completion ? 

### ISSUE THREAD

**Issue by v-wewei** [paul007pl/VRCNet#12]

**Comment by v-wewei** [comment]
single you only provide the 2048 point completion config, I would like to ask that  if we should modify some other parameters except for the num_points parameter.

**Comment by paul007pl** [comment]
Well... Different methods should have different settings.
As for VRCNet, you can try to set (if I remember correctly)

num_coarse_raw: 1024
num_fps: 16384
num_coarse: 16384

If you have a powerful machine, you can also try to use more branches, by add more "knn" in the "knn_list".
Other configurations can also be tested.
Hope that helps~

**Comment by v-wewei** [comment]
Thanks for your reply !
