### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by Marigod98** [paul007pl/VRCNet#19]
Hi,
Thank you for the amazing work.just some questions about the dataset, I notice   there are  six groups in mvp_test_gt_%dpts.h5:
'complete_pcds',  'labels',  'normal',  'novel_complete_pcds',  'novel_labels',  'novel_normal'
I want to use the 'normal' data for some other tasks, so can you tell me how did you get 'normal',  Is it same as the normal of shapenet dataset? and  what does 'novel' mean? what is the difference between 'novel_complete_pcds'  and 'complete_pcds'?
Thanks in advance.

**Comment by paul007pl** [comment]
Thanks for asking.
If I did not remember wrongly, the 'normal' data are obtained by using an Open3D function.
'complete' means complete point clouds for the first 8 categories, and 'novel_complete' means complete point clouds for the rest 8 categories.  It is suggested to try another experiment setting, that is training with the first 8 category point clouds, and then evaluate on the rest 8 unseen (novel) categories.

**Comment by Marigod98** [comment]
thanks for your reply!
