### ISSUE TITLE
Questions about Poisson disk sampling

### ISSUE THREAD

**Issue by walsvid** [paul007pl/VRCNet#2]
Hi, thank you very much for providing the model and dataset. 

I notice in the article that the MVP dataset sampled point clouds of different resolutions on the same 3D model. I wonder what tools or libraries you use to Poisson disk sampling? So that the number of point clouds in MVP dataset can be controlled to be the same. 

I tried to use meshlab but I cannot guarantee that the number of point clouds sampled by multiple 3D models are the same. Could you provide the code to sample the dataset?

**Comment by paul007pl** [comment]
Hi Chao Wen,
If I did not remember wrongly, please try open3d:
http://www.open3d.org/docs/0.7.0/python_api/open3d.geometry.sample_points_poisson_disk.html
Good Luck~
