### ISSUE TITLE
Training outputs in vrcnet

### ISSUE THREAD

**Issue by stefano-mazz** [paul007pl/VRCNet#20]
Hi, i have a question about the output dimensions during training. Is it true that fine and course ptc have dimension [2*batch_size, numberOfPoints, 3], since  the decoder during training has twice the features and twice the partial cloud as input? 
I'm trying to implement it on another dataset and i do not understand it.
Thank you in advance.

**Comment by paul007pl** [comment]
Hi, you are right.  During training, we try two parallel pipelines: 1. one for reconstruction; 2. one for completion, and that is the reason you found the batch_size is double.

**Comment by stefano-mazz** [comment]
So, it is used only for the loss computation. Ok i understand thank you!
