### ISSUE TITLE
Pretrianed

### ISSUE THREAD

**Issue by hy-cn** [paul007pl/VRCNet#21]
Thank you for your open source code！How can I use the pretrained data?I'm major in vehicle engineering but not computer vision.So this question really confuse me a lot.

**Comment by paul007pl** [comment]
Maybe you can first try to Google or Baidu: "how to load pretrained model in pytorch"
Then, you can try to use the provided test.py file to evaluate.
Remember to change the pretrained file path in the corresponding config file.

**Comment by hy-cn** [comment]
> Maybe you can first try to Google or Baidu: "how to load pretrained model in pytorch" Then, you can try to use the provided test.py file to evaluate. Remember to change the pretrained file path in the corresponding config file.

Thanks for your reply.I have been training MVPdataset for 50 hours at batchsize=2.But only 8 epoch have finished.Can I finish it in ten days?

**Comment by paul007pl** [comment]
It seems like you do not have a good GPU... If that is the case, I would suggest trying simpler architectures...
