### ISSUE TITLE
some question about evaluate

### ISSUE THREAD

**Issue by peng666** [paul007pl/VRCNet#7]
Hello, I run the code several times, the result of PCN is only cd_t=0.000978, but the result of your paper is 6.02 (CD loss multiplied by 10^4). Is this result reasonable?

**Comment by peng666** [comment]
Thank you. I have solved it. Thank you for your work

**Comment by ToddBear** [comment]
@peng666 I met the same problems. can you please tell me how you solved it ?  Thank you.

**Comment by paul007pl** [comment]
I guess it is caused by different random initializations, and maybe you can train it again.

**Comment by SuperDouble** [comment]
> Hello, I run the code several times, the result of PCN is only cd_t=0.000978, but the result of your paper is 6.02 (CD loss multiplied by 10^4). Is this result reasonable?

hello, how to solve this problem?
