### ISSUE TITLE
VRCNet training

### ISSUE THREAD

**Issue by lkhazyf** [paul007pl/VRCNet#8]
Thanks very much for share the codes. I am a little confused about the vrcnet. Why the codes in vrc.py are the same as vrcnet.py? According to the paper, three steps (PMNET trained with gt, PMNET trained with incompletion point clouds, RENET) are needed if we reproduce it. However, only one file ( vrc.py or vrcnet.py) is provided. Should I revise it?  Thanks again.

**Comment by paul007pl** [comment]
Our model is trained end-to-end.  In other words, you do not need to perform three independent steps.
I have removed the duplicated files.  Thank you~
