### ISSUE TITLE
F-score

### ISSUE THREAD

**Issue by peng666** [paul007pl/VRCNet#9]
Why is my F-Score as high as 90%, but the F-Score in your article is about 80%? The code is the source code provided by this repository.

**Comment by paul007pl** [comment]
It is caused by a different predefined threshold, and I have revised now.  And you can also change it in your local repository (in fscore.py, set threshold=0.0001).  BTW, we are going to host a point cloud completion chanllenge in ICCV2021 workshop, which will start soon.  Welcome to attend~
